### PR TITLE
Updated themes with base16-builder

### PR DESCRIPTION
**Pull request by weslly**
Rebuilt existing themes and added new ones.

### CODE REVIEW

**Comment by chriskempson** [comment]
Thanks very much. I don't have a Mac anymore so I could really do with finding someone else willing to be the maintainer for this repo.

**Comment by davidosomething** [comment]
Not working for me! tomorrow dark/light are reversed and inaccurate

**Comment by weslly** [comment]
@chriskempson I'm willing to help maintaining if you are interested

**Comment by weslly** [comment]
@davidosomething The builder script generates a dark and light variation for all themes, the tomorrow-dark theme is just a variant of the light theme, you probably want to use the "Tomorrow Night" theme.

**Comment by davidosomething** [comment]
ah you're right, thanks

**Comment by chriskempson** [comment]
@weslly All that's needed is a bit of a restructure (needs an output folder for generated output and the template file porting from the original base16-builder repo, see: https://github.com/chriskempson/base16-vim for an example of how this repo should look). Finally it's just a case of swapping my handle for yours here: https://github.com/chriskempson/base16#template-repositories and updating the templates source file here: https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml.

**Pull request merged**
